language: node_js
os: linux
sudo: false
dist: trusty
bundler_args: --retry 5
node_js:
  - "7"
env:
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
git:
  submodules: false
before_install:
  - sudo apt-get install -y xserver-xorg-dev libxext-dev libxi-dev
install:
  - npm install --silent -g phantomjs-prebuilt
  - npm install --silent -g casperjs
  - npm install --silent -g slimerjs
  - npm install --silent -g gl
edge: true
notifications:
  slack: metacell:5ALSeoP88DqIhORUJvxE56sq
services:
- docker
addons:
  firefox: "58.0"
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export SLIMERJSLAUNCHER=/home/travis/firefox-58.0/firefox/firefox
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
  - export HNN_BRANCH="development";
  - value=$(git ls-remote --heads https://github.com/MetaCell/HNN-UI $TRAVIS_BRANCH | wc -l)
  - if [ $value -eq 1 ]; then echo $TRAVIS_BRANCH; export HNN_BRANCH=$TRAVIS_BRANCH; fi
  - echo $HNN_BRANCH

script:
  - travis_wait travis_retry docker build -t="hnn-ui" github.com/MetaCell/HNN-UI#${HNN_BRANCH} -f="./Dockerfile_dev"
  - travis_retry docker run  -t -dit --name=hnn-ui_container -h localhost -p 8888:8888 hnn-ui:latest
  - cd $TRAVIS_BUILD_DIR/ && ls
  - cd tests
  - bash utilities/hnn-server-status.sh
  - sleep 30
  - http_status=$(curl -s -I $1 http://localhost:8888/geppetto | grep HTTP/1.1 | awk {'print $2'})
  - echo "$http_status"
  - while [ "$http_status" == "404" ]; do
    echo "Restart run";
    echo "Printing logs for debugging purposes";
    docker stop $(docker ps -a -q);
    docker rm $(docker ps -a -q);
    docker run  -t -dit --name=hnn-ui_container -h localhost -p 8888:8888 hnn-ui:latest
    bash utilities/hnn-server-status.sh
    sleep 30;
    http_status=$(curl -s -I $1 http://localhost:8888/geppetto | grep HTTP/1.1 | awk {'print $2'})
    echo "Done restarting";
    echo "$http_status";
    done;
  - http_status=$(curl -s -I $1 http://localhost:28081 | grep HTTP/1.1 | awk {'print $2'})
  - echo "$http_status";
  - "curl -s -I $1 http://localhost:8888/geppetto | grep HTTP/1.1 | awk {'print $2'}"
  - firefox --version
  - travis_retry xvfb-run -a --server-args="-screen 0 1024x768x24"  casperjs test hnn-tests.js --host=http://localhost:8888/ --engine=slimerjs
  - docker logs -t hnn-ui_container
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
